In [1]:
import numpy as np

NumPy 通常与 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用， 这种组合广泛用于替代 MatLab，是一个强大的科学计算环境，  
有助于我们通过 Python 学习数据科学或者机器学习。 

SciPy 是一个开源的 Python 算法库和数学工具包。  

SciPy 包含的模块有最优化、线性代数、积分、插值、特殊函数、快速傅里叶变换、信号处理和图像处理、常微分方程求解和其他科学与工程中常用的计算。  

Matplotlib 是 Python 编程语言及其数值数学扩展包 NumPy 的可视化操作界面。   
它为利用通用的图形用户界面工具包，如 Tkinter, wxPython, Qt 或 GTK+ 向应用程序嵌入式绘图提供了应用程序接口（API）。

In [2]:
#b = np.random.randint(1,10,size=(3,4))  #创建随机整数（数组）
b = np.random.randint(1,10,8)  #创建随机整数（数组）
b

array([8, 5, 6, 6, 4, 2, 8, 5])

In [3]:
print(b)

[8 5 6 6 4 2 8 5]


In [4]:
np.random.choice(b,(3,2),replace=False) #replace =False时，选取元素不会再选取

array([[5, 6],
       [5, 2],
       [8, 8]])

- uniform(low, high, size) : 产生均匀分布的数组，起始值为low，high为结束值，size为形状 
- normal(loc, scale, size) : 产生正态分布的数组， loc为均值，scale为标准差，size为形状 
- poisson(lam, size) : 产生泊松分布的数组， lam随机事件发生概率，size为形状 
- eg: a = np.random.uniform(0, 10, (3, 4)) a = np.random.normal(10, 5, (3, 4))
--------------------

## numpy的统计函数
sum(a, axis = None) : 依给定轴axis计算数组a相关元素之和，axis为整数或者元组  
mean(a, axis = None) : 同理，计算平均值    
average(a, axis =None, weights=None) : 依给定轴axis计算数组a相关元素的加权平均值  
std（a, axis = None） ：同理，计算标准差  
var（a, axis = None）: 计算方差  
> eg： np.mean(a, axis =1) ： 对数组a的第二维度的数据进行求平均  

a = np.arange(15).reshape(3, 5)  
np.average(a, axis =0, weights =[10, 5, 1])   
对a第一各维度加权求平均，weights中为权重，注意要和a的第一维匹配  
min(a) max(a) : 计算数组a的最小值和最大值  
argmin(a) argmax(a) : 计算数组a的最小、最大值的下标（注：是一维的下标）  
unravel_index(index, shape) : 根据shape将一维下标index转成多维下标  
ptp(a) : 计算数组a最大值和最小值的差  
median(a) : 计算数组a中元素的中位数（中值）  
>eg：a = [[15, 14, 13], 
[12, 11, 10] ]  
np.argmax(a) –> 0   
np.unravel_index( np.argmax(a), a.shape) –> (0,0)  

In [14]:
#PIL， python image library 库  
from PIL import Image  
#Image是PIL库中代表一个图像的类（对象） 

im = np.array(Image.open("xxx.jpg"))  
im = Image.fromarray(b.astype("uint8")) # 生成   
im.save("路径.jpg") # 保存  
im = np.array(Image.open(".jpg").convert("L")) # convert(‘L’)表示转为灰度图  

IndexError: tuple index out of range

In [1]:
x=np.random.randint(0, 5, [4,3,2,2])
#print(x)

NameError: name 'np' is not defined