In [88]:
import pandas as pd
import numpy as np
data = [[-1,1,2],[-2,3,1],[4,0,3]]
a=np.array(data)
print(type(a))
#输出行数
print(a.shape[0])
#输出列数
print(a.shape[1])

<class 'numpy.ndarray'>
3
3


In [99]:
c = np.zeros([a.shape[1], a.shape[1]])
print(c)
for i in range(a.shape[1]):
    print(a[:,i])
    print("第{0}列的mean值:{1}".format(i,np.mean(a[:,i])))
    #print(i)
    
    for j in range(a.shape[1]):
        print("J:{0} mean值:{1}".format(j,np.mean(a[:,j])))
        c[i,j]=sum((a[:,i]-np.mean(a[:,i]))*(a[:,j]-np.mean(a[:,j])))/(a.shape[1]-1)
#       print(c)

print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[-1 -2  4]
第0列的mean值:0.3333333333333333
J:0 mean值:0.3333333333333333
J:1 mean值:1.3333333333333333
J:2 mean值:2.0
[1 3 0]
第1列的mean值:1.3333333333333333
J:0 mean值:0.3333333333333333
J:1 mean值:1.3333333333333333
J:2 mean值:2.0
[2 1 3]
第2列的mean值:2.0
J:0 mean值:0.3333333333333333
J:1 mean值:1.3333333333333333
J:2 mean值:2.0
[[10.33333333 -4.16666667  3.        ]
 [-4.16666667  2.33333333 -1.5       ]
 [ 3.         -1.5         1.        ]]


In [28]:
fruits = ['banana', 'apple',  'mango']
print(len(fruits))
for index in range(len(fruits)):
   print( '当前水果 :', fruits[index])
 
print("Good bye!")

3
当前水果 : banana
当前水果 : apple
当前水果 : mango
Good bye!
